"""Generate CondoCompare.astro with its dataset emitted mechanically from live.json."""
import io, json

rows = json.load(io.open('cmp_rows.json', encoding='utf-8'))
DATA = json.dumps(rows, separators=(',', ':'), ensure_ascii=False)

HEAD = '''---
// Compare up to three condominiums, side by side, on what the public record can actually say.
//
// ROWS is emitted mechanically from data/live.json in the sg-property-decision repo (URA
// PMI_Resi_Transaction resale medians per project, twelve months to August 2026; nearest MRT from
// LTA station exits; district size-band medians from the same feed). Generated by
// scripts/gen_condo_compare.py, never hand-typed; the count, the district coverage and every
// derived figure are recomputed from ROWS so prose cannot drift from bars.
//
// INCLUSION RULE, mechanical and stated on the figure: at least 10 resales in the twelve months.
// 309 of about 1,135 condominiums clear it. Below that a median moves on one unusual unit, and a
// comparison offering a number resting on two sales is worse than one that declines to.
//
// WHICH ONE IS AHEAD, AND BY HOW MUCH — the point of the redesign. Bars alone made the reader
// eyeball three lengths and guess the margin. Every cell now carries an explicit delta, and each
// measure declares whether it even HAS a better end:
//
//   more  — longer lease, more resales. More is unambiguously more of the thing.
//   less  — distance to a station. Nearer is unambiguously nearer.
//   none  — price psf, standing vs district, unit size, typical quantum. These have NO better
//           end: cheaper suits a buyer and dearer is what the market pays; a big flat is right
//           for one household and wrong for the next. For these the tool reports the spread and
//           refuses to name a leader, because doing so would be inventing a preference.
//
// There is deliberately NO composite score. Summing these into a winner would be a ranked league
// table, which the venture's red lines prohibit and which would be dishonest anyway — the weights
// are the reader's and nobody else's. The figure says so in as many words.
//
// COLOUR MEANS SEGMENT AND NOTHING ELSE (VOICE.md C10), reusing the validated triple from
// DistrictYieldChart and DistrictSupplyChart: light #2563EB/#B45309/#7C3AED. Leadership is marked
// by a text tag, never by hue, so it survives greyscale and colour blindness and never implies a
// value judgement the data cannot support.
//
// The class prefix is `cmp-`, not `cc-`: src/pages/cashback-calendar.astro already owns `cc-` and
// both files ship `is:global` styles, so sharing a prefix would collide the moment they met.
const ASOF = 'August 2026';
const MIN_SALES = 10;
const TOTAL_PROJECTS = 1135;

interface Row { p: string; d: string; n: string; g: 'CCR' | 'RCR' | 'OCR'; psf: number; v: number;
  l: number | string; m: number; x: string; s: number; b: number; q: number }

const ROWS: Row[] = __DATA__;

const DISTRICTS = [...new Set(ROWS.map((r) => r.d))]
  .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)));
const BY_D = DISTRICTS.map((d) => ({
  d,
  name: ROWS.find((r) => r.d === d).n,
  items: ROWS.filter((r) => r.d === d).sort((a, b) => a.p.localeCompare(b.p)),
}));

// The opening three. Callers may pass their own via the `defaults` prop — an article about one
// project wants its own neighbourhood, the standalone page wants no local bias — but a name that
// is not in ROWS is dropped rather than silently rendering an empty column, and the data's own
// answer (most traded) fills any gap.
interface Props { defaults?: string[] }
const BY_VOLUME = [...ROWS].sort((a, b) => b.v - a.v).map((r) => r.p);
const asked = (Astro.props.defaults ?? []).filter((name) => ROWS.some((r) => r.p === name));
const DEFAULTS = [...asked, ...BY_VOLUME.filter((p) => !asked.includes(p))].slice(0, 3);

const SEGS = [{ k: 'OCR', label: 'Outside central' }, { k: 'RCR', label: 'Rest of central' },
              { k: 'CCR', label: 'Core central' }];
const SLOTS = ['First', 'Second', 'Third'];
const n = (v) => v.toLocaleString('en-SG');
---
'''

BODY = r'''
<figure class="cmp">
  <figcaption class="cmp-cap">
    <h4>Compare three, on the public record</h4>
    <p>Seven measures, {n(ROWS.length)} condominiums, {DISTRICTS.length} districts, twelve months
    to {ASOF}. Three of the seven have a better end and are marked with it. Four do not, and say so.</p>
  </figcaption>

  <div class="cmp-picks">
    {[0, 1, 2].map((i) => (
      <div class="cmp-pick">
        <label for={`cmp-s${i}`}>{SLOTS[i]}</label>
        <select id={`cmp-s${i}`}>
          <option value="">&mdash; none &mdash;</option>
          {BY_D.map((grp) => (
            <optgroup label={`${grp.d} · ${grp.name}`}>
              {grp.items.map((r) => (
                <option value={r.p} selected={r.p === DEFAULTS[i]}>{r.p}</option>
              ))}
            </optgroup>
          ))}
        </select>
      </div>
    ))}
  </div>

  <div class="cmp-legend">
    {SEGS.map((s) => (<span class="cmp-lg"><i class={`cmp-dot ${s.k}`}></i>{s.label}</span>))}
    <span class="cmp-hint">colour marks segment &middot; <b>ahead</b> marks the leading value</span>
  </div>

  <div class="cmp-out" id="cmp-out" aria-live="polite"></div>

  <p class="cmp-say" id="cmp-say"></p>

  <p class="cmp-src">Computed by us from URA private resale transactions and LTA station-exit
  locations, twelve months to {ASOF}. <b>A project appears only if at least {MIN_SALES} units
  resold in that period</b> &mdash; {n(ROWS.length)} of about {n(TOTAL_PROJECTS)} condominiums clear
  that, so this is the liquid end of the market, not a full list. Every price is a <b>median of what
  traded</b>, mixing floor, stack, facing, condition and renovation, so it is not a valuation of any
  particular unit. Distances are straight-line to the nearest station entrance; a real walk is
  typically 20&ndash;40% further. &ldquo;Against its district&rdquo; compares a project with resale
  of the <b>same size band</b> in the same district &mdash; a position, not a discount, which a
  newer building, a higher floor or a shorter walk can each explain. <b>There is no overall score
  and there will not be one</b>: the weights belong to whoever is buying.</p>
</figure>

<script is:inline define:vars={{ ROWS }}>
(function(){
const $ = id => document.getElementById(id);
const sgd = v => 'S$' + Math.round(v).toLocaleString('en-SG');
const num = v => Math.round(v).toLocaleString('en-SG');
const BY = Object.fromEntries(ROWS.map(r => [r.p, r]));
const esc = s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

// `dir` is the honest part. 'more'/'less' name a direction the data genuinely has; 'none' means
// the measure has no better end and the tool must not invent one. `lead` is the word used for the
// front-runner — factual ("longest lease"), never evaluative ("best").
const METRICS = [
  { label: 'Median resale price', dir: 'none', lead: '',
    fmt: r => sgd(r.psf) + ' psf', val: r => r.psf,
    delta: (v, ref) => pctDelta(v, ref),
    note: 'no better end \u2014 cheaper suits a buyer, dearer is what the market pays' },
  { label: 'Against its district', dir: 'none', lead: '',
    fmt: r => signed((r.psf / r.b - 1) * 100) + '%', val: r => r.psf / r.b - 1,
    delta: (v, ref) => ppDelta(v * 100, ref * 100),
    note: 'no better end \u2014 a position vs same-size resale nearby, not a discount' },
  { label: 'Resales in 12 months', dir: 'more', lead: 'most traded',
    fmt: r => num(r.v), val: r => r.v,
    delta: (v, ref) => absDelta(v, ref, ''),
    note: 'more changes of hand = easier to leave when you need to' },
  { label: 'Lease remaining', dir: 'more', lead: 'longest',
    fmt: r => r.l === 'FH' ? 'Freehold' : r.l + ' yrs',
    val: r => r.l === 'FH' ? 999 : Number(r.l),
    delta: (v, ref) => (v >= 999 || ref >= 999) ? ''
      : absDelta(v, ref, Math.abs(v - ref) === 1 ? ' yr' : ' yrs'),
    note: 'more years is more, and under 60 the CPF and lending rules tighten' },
  { label: 'To the nearest MRT', dir: 'less', lead: 'nearest',
    fmt: r => num(r.m) + ' m \u00b7 ' + r.x, val: r => r.m,
    delta: (v, ref) => absDelta(v, ref, ' m'),
    note: 'nearer is nearer \u2014 whether that beats quiet is yours to weigh' },
  { label: 'Size that actually trades', dir: 'none', lead: '',
    fmt: r => num(r.s) + ' sq ft', val: r => r.s,
    delta: (v, ref) => absDelta(v, ref, ' sq ft'),
    note: 'no better end \u2014 the right size is the one you need' },
  { label: 'Typical price paid', dir: 'none', lead: '',
    fmt: r => sgd(r.q), val: r => r.q,
    delta: (v, ref) => pctDelta(v, ref),
    note: 'no better end \u2014 it tracks the size that trades as much as the price' },
];

function signed(x){ return (x >= 0 ? '+' : '\u2212') + Math.abs(x).toFixed(0); }
function absDelta(v, ref, unit){
  const d = v - ref;
  if (Math.round(Math.abs(d)) === 0) return 'same';
  return signed(d) + unit;
}
function pctDelta(v, ref){
  if (!ref) return '';
  const d = (v / ref - 1) * 100;
  if (Math.abs(d) < 0.5) return 'same';
  return signed(d) + '%';
}
function ppDelta(v, ref){
  const d = v - ref;
  if (Math.abs(d) < 0.5) return 'same';
  return signed(d) + ' pp';
}

function render(){
  const picked = [0,1,2].map(i => BY[$('cmp-s'+i).value]).filter(Boolean);
  if (!picked.length){
    $('cmp-out').innerHTML = '<p class="cmp-empty">Choose at least one building to compare.</p>';
    $('cmp-say').textContent = '';
    return;
  }
  const cols = picked.length;
  let h = '<div class="cmp-heads" style="--cols:' + cols + '">';
  picked.forEach(r => {
    h += '<div class="cmp-head"><b>' + esc(r.p) + '</b><span class="cmp-meta"><i class="cmp-dot '
      + r.g + '"></i>' + r.d + ' \u00b7 ' + r.g + '</span></div>';
  });
  h += '</div>';

  METRICS.forEach(mt => {
    const vals = picked.map(mt.val);
    const max = Math.max.apply(null, vals);
    const min = Math.min.apply(null, vals);
    // Reference for the delta: the leader where one exists, otherwise the lowest value, so the
    // column reads as "how far from the front" or "how far above the cheapest".
    const isLead = i => cols > 1 && mt.dir !== 'none'
      && (mt.dir === 'more' ? vals[i] === max : vals[i] === min);
    const ref = mt.dir === 'more' ? max : mt.dir === 'less' ? min : min;
    const refLabel = mt.dir === 'none' ? 'vs lowest here' : 'from the front';
    // Bars stay proportional to the value, never to the gap: exaggerating a small spread to fill
    // the track would make two near-identical buildings look far apart.
    const scale = max || 1;

    h += '<div class="cmp-metric"><div class="cmp-mlabel">' + mt.label
       + (mt.dir === 'none' ? '<span class="cmp-tag cmp-tag-n">no better end</span>' : '')
       + '<em>' + mt.note + '</em></div>'
       + '<div class="cmp-mrows" style="--cols:' + cols + '">';
    picked.forEach((r, i) => {
      const lead = isLead(i);
      // On a measure with no better end the reference cell is simply the lowest of the three,
      // and saying "same" about a value compared with itself reads as a bug. Name it instead.
      const isRef = mt.dir === 'none' && vals[i] === ref;
      const d = cols > 1 && !lead
        ? (isRef ? (cols > 1 ? 'lowest here' : '') : mt.delta(vals[i], ref))
        : '';
      h += '<div class="cmp-cell"><span class="cmp-v">' + esc(mt.fmt(r)) + '</span>'
        + '<span class="cmp-track"><span class="cmp-bar ' + r.g + '" style="width:'
        + Math.max(2, (vals[i] / scale) * 100) + '%" role="img" aria-label="'
        + esc(r.p + ', ' + mt.label + ': ' + mt.fmt(r) + (lead ? ', ' + mt.lead : '')
              + (d ? ', ' + d + ' ' + refLabel : '') + '.') + '"></span></span>'
        + (lead ? '<span class="cmp-delta cmp-lead">\u25B2 ' + mt.lead + '</span>'
                : d ? '<span class="cmp-delta">' + d + '</span>' : '<span class="cmp-delta"></span>')
        + '</div>';
    });
    h += '</div></div>';
  });
  $('cmp-out').innerHTML = h;

  if (cols < 2){
    $('cmp-say').innerHTML = 'Add a second building and every row will show how far apart they are.';
    return;
  }
  // Count leads only across the measures that HAVE a direction. This is a tally, not a score:
  // it is never summed with the four that do not, and it is stated as such.
  const dirMetrics = METRICS.filter(m => m.dir !== 'none');
  const tally = picked.map(r => dirMetrics.filter(mt => {
    const vals = picked.map(mt.val);
    const v = mt.val(r);
    return mt.dir === 'more' ? v === Math.max.apply(null, vals) : v === Math.min.apply(null, vals);
  }).length);
  const parts = picked.map((r, i) => '<b>' + esc(r.p) + '</b> ' + tally[i]);
  $('cmp-say').innerHTML = 'On the ' + dirMetrics.length + ' measures that have a better end '
    + '(lease, liquidity, distance), the count runs ' + parts.join(' &middot; ') + '. '
    + 'The other four have no better end, so they are reported and not scored &mdash; and the three '
    + 'that do are not worth the same to everyone, which is why this tool will not add them up for '
    + 'you. What none of it can tell you is which unit, on which floor, facing what, and that is '
    + 'usually the difference that decides a purchase.';
}

function init(){
  [0,1,2].forEach(i => $('cmp-s'+i).addEventListener('change', render));
  render();
}
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
else init();
})();
</script>

<style is:global>
.cmp{
  --cmp-ocr:#2563EB; --cmp-rcr:#B45309; --cmp-ccr:#7C3AED;   /* validated triple, light card */
  --cmp-ink:var(--color-dark); --cmp-body:var(--color-body); --cmp-muted:var(--color-muted);
  --cmp-rule:var(--color-border); --cmp-soft:#F0ECE2;
  --cmp-mono:var(--font-mono),'SF Mono',Menlo,Consolas,monospace;
  margin:26px 0;padding:20px 22px 16px;background:#fff;
  border:1px solid var(--cmp-rule);border-radius:12px
}
/* No dark-scheme override: the card is pinned white in both schemes, so the ink follows the card
   rather than the page, and the triple is the light-card variant for that reason. */
.post-content .cmp-cap{margin:0 0 14px;padding:0;text-align:left}
.post-content .cmp-cap h4{margin:0 0 3px;font-size:15.5px;font-weight:700;color:var(--cmp-ink);
  font-family:var(--font-body);letter-spacing:0}
.post-content .cmp-cap p{margin:0;font-size:12.5px;color:var(--cmp-muted);line-height:1.5}

.cmp-picks{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:12px}
.cmp-pick label{display:block;font-size:11px;font-weight:700;text-transform:uppercase;
  letter-spacing:.05em;color:var(--cmp-muted);margin-bottom:4px}
.cmp select{width:100%;font-family:inherit;font-size:12.5px;color:var(--cmp-ink);background:#fff;
  border:1px solid var(--cmp-rule);border-radius:6px;padding:11px 8px;min-height:44px}
.cmp select:focus-visible{outline:2px solid var(--cmp-ink);outline-offset:2px}

.cmp-legend{display:flex;flex-wrap:wrap;gap:6px 16px;align-items:center;margin-bottom:12px;font-size:11.5px}
.cmp-lg{display:flex;align-items:center;gap:6px;color:var(--cmp-body)}
.cmp-dot{width:9px;height:9px;border-radius:50%;display:inline-block;flex:0 0 auto}
.cmp-dot.OCR{background:var(--cmp-ocr)} .cmp-dot.RCR{background:var(--cmp-rcr)} .cmp-dot.CCR{background:var(--cmp-ccr)}
.cmp-hint{color:var(--cmp-muted)}

.cmp-heads,.cmp-mrows{display:grid;grid-template-columns:repeat(var(--cols),1fr);gap:10px}
.cmp-heads{padding-bottom:8px;border-bottom:1px solid var(--cmp-rule);margin-bottom:10px}
.cmp-head b{display:block;font-size:13px;color:var(--cmp-ink);line-height:1.25}
.cmp-meta{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--cmp-muted);margin-top:2px}

.cmp-metric{margin-bottom:13px}
.cmp-mlabel{font-size:11.5px;font-weight:600;color:var(--cmp-body);margin-bottom:5px}
.cmp-mlabel em{display:block;font-style:normal;font-weight:400;font-size:11px;color:var(--cmp-muted)}
.cmp-tag{display:inline-block;margin-left:6px;font-size:11px;font-weight:600;letter-spacing:.01em;
  border:1px solid var(--cmp-rule);border-radius:999px;padding:0 7px;color:var(--cmp-muted)}
.cmp-cell{min-width:0}
.cmp-v{display:block;font-family:var(--cmp-mono);font-variant-numeric:tabular-nums;font-size:12px;
  font-weight:600;color:var(--cmp-ink);margin-bottom:3px}
.cmp-track{display:block;height:9px;background:var(--cmp-soft);border-radius:3px}
.cmp-bar{display:block;height:9px;border-radius:3px;min-width:2px}
.cmp-bar.OCR{background:var(--cmp-ocr)} .cmp-bar.RCR{background:var(--cmp-rcr)} .cmp-bar.CCR{background:var(--cmp-ccr)}
.cmp-delta{display:block;min-height:15px;margin-top:3px;font-family:var(--cmp-mono);
  font-variant-numeric:tabular-nums;font-size:11px;color:var(--cmp-muted)}
/* Leadership is a word, never a colour: it must survive greyscale and colour blindness, and a
   green "winner" would assert a preference the data cannot support. */
.cmp-lead{color:var(--cmp-ink);font-weight:700}
.post-content p.cmp-empty{margin:0;font-size:12.5px;color:var(--cmp-muted)}

.post-content p.cmp-say{margin:14px 0 0;padding-top:12px;border-top:1px solid var(--cmp-rule);
  font-size:12.5px;line-height:1.6;color:var(--cmp-body)}
.post-content p.cmp-src{margin:10px 0 0;padding-top:10px;border-top:1px solid var(--cmp-rule);
  font-size:11.5px;line-height:1.55;color:var(--cmp-muted)}

@media (max-width:640px){
  .cmp{padding:16px 14px 13px}
  .cmp-picks{grid-template-columns:1fr;gap:8px}
  .cmp-hint{display:none}
  .cmp-head b{font-size:12px}
  /* Three columns leave ~102px each on a phone, which truncated the longest value
     ("388 m · Queenstown") and ate the station name. Values wrap instead of ellipsing;
     uneven cell heights are harmless because each measure is its own block. */
  .cmp-v{font-size:11px;white-space:normal;line-height:1.3}
  .cmp-mlabel{font-size:11px}
  .cmp-mlabel em{font-size:11px}
  .cmp-delta{font-size:11px}
}
</style>
'''

out = HEAD.replace('__DATA__', DATA) + BODY
path = r'C:\TheEnoughPoint-wt-newlaunch\src\components\CondoCompare.astro'
io.open(path, 'w', encoding='utf-8').write(out)
print('written', len(out), 'bytes ·', len(rows), 'projects ·', len({r['d'] for r in rows}), 'districts')
