"""The Astro frontmatter for CondoCompare.astro. Data and provenance are injected by
gen_compare.py; this file holds only the template."""

HEAD = '''---
// DATA PROVENANCE: __PROVENANCE__
// Regenerate with scripts/gen_compare.py — never edit this file by hand.
// Compare up to three condominiums, side by side, on what the public record can actually say.
//
// ROWS is emitted mechanically from data/live.json in the sg-property-decision repo (URA
// PMI_Resi_Transaction resale medians per project, twelve months to August 2026; nearest MRT from
// LTA station exits; district size-band medians from the same feed). Generated by
// scripts/gen_condo_compare.py, never hand-typed; the count, the district coverage and every
// derived figure are recomputed from ROWS so prose cannot drift from bars.
//
// INCLUSION RULE, mechanical and stated on the figure: at least 10 resales in the twelve months.
// 309 of about 1,135 condominiums clear it. Below that a median moves on one unusual unit, and a
// comparison offering a number resting on two sales is worse than one that declines to.
//
// WHICH ONE IS AHEAD, AND BY HOW MUCH — the point of the redesign. Bars alone made the reader
// eyeball three lengths and guess the margin. Every cell now carries an explicit delta, and each
// measure declares whether it even HAS a better end:
//
//   more  — longer lease, more resales. More is unambiguously more of the thing.
//   less  — distance to a station. Nearer is unambiguously nearer.
//   none  — price psf, standing vs district, unit size, typical quantum. These have NO better
//           end: cheaper suits a buyer and dearer is what the market pays; a big flat is right
//           for one household and wrong for the next. For these the tool reports the spread and
//           refuses to name a leader, because doing so would be inventing a preference.
//
// There is deliberately NO composite score. Summing these into a winner would be a ranked league
// table, which the venture's red lines prohibit and which would be dishonest anyway — the weights
// are the reader's and nobody else's. The figure says so in as many words.
//
// COLOUR SHOWS RELATIVE STANDING WITHIN EACH ROW — never who the building is.
//
// Two earlier attempts were both wrong, and the second failed in a way worth recording.
//
// First it marked market segment, which the article's own default exposed: three District 20
// buildings are all RCR, so all three bars came out identical and the channel carried nothing.
//
// Then it identified the building — one hue per column, blue/orange/aqua. That answered "which
// column is which" but introduced a fairness problem: those hues are not emotionally neutral. The
// building that happened to be picked third got the green one. Nobody chose that, and no reader
// can un-see it. A comparison tool that hands out a favourable tone by slot order is putting a
// thumb on the scale by accident, which is worse than doing it on purpose.
//
// A blue ordinal ramp followed, which was fair but inert — the reader could not tell at a glance
// whether a dark cell was good news. On ZH's call the figure now uses STATUS colour, and the
// scope of that decision is the whole design:
//
//   ranked rows    green leads, red trails, the middle stays neutral. Only the three measures
//                  that HAVE a better end are marked.
//   unranked rows  no status colour at all. Price, standing-vs-district, unit size and typical
//                  quantum have no better end, so green there would invent a preference. This is
//                  not a hedge — it is what stops the figure becoming a scorecard for a named
//                  development, which is the one thing this tool must never be.
//
// Status tokens come from the fixed scale and are not themed: good #136c2c, critical #a8231c. Per
// the status rule they never appear as colour alone — every marked cell also carries an arrow and
// a factual word ("longest", "furthest", never "best"), so the reading survives greyscale, colour
// blindness and a monochrome print. Measured on the page: the green mark reads 3.02:1 on its own
// wash and the red 4.22:1, with values at about 15:1 on both.
//
// THE BARS ARE GONE, and that is the other half of the rethink. Twenty-one of them, each
// normalised to its own row so none could be compared with any other, read as wallpaper rather
// than as information. A tinted cell says the same thing in a third of the height — the component
// lost about a quarter of its length and gained the thing it was missing, which is a reader being
// able to see the shape of the trade without reading every number.
//
// The class prefix is `cmp-`, not `cc-`: src/pages/cashback-calendar.astro already owns `cc-` and
// both files ship `is:global` styles, so sharing a prefix would collide the moment they met.
const ASOF = 'August 2026';
const MIN_SALES = 10;
const TOTAL_PROJECTS = 1135;

interface Row { p: string; d: string; n: string; psf: number; v: number;
  fh: 0 | 1; lyr: number | null; m: number; x: string; s: number; b: number; q: number;
  lo: number; hi: number; mo: number | null }

const ROWS: Row[] = __DATA__;

const DISTRICTS = [...new Set(ROWS.map((r) => r.d))]
  .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)));
const BY_D = DISTRICTS.map((d) => ({
  d,
  name: ROWS.find((r) => r.d === d).n,
  items: ROWS.filter((r) => r.d === d).sort((a, b) => a.p.localeCompare(b.p)),
}));

// The opening three. Callers may pass their own via the `defaults` prop — an article about one
// project wants its own neighbourhood, the standalone page wants no local bias — but a name that
// is not in ROWS is dropped rather than silently rendering an empty column, and the data's own
// answer (most traded) fills any gap.
interface Props { defaults?: string[]; reference?: boolean }
const BY_VOLUME = [...ROWS].sort((a, b) => b.v - a.v).map((r) => r.p);
const REFON = Astro.props.reference === true;
const asked = (Astro.props.defaults ?? []).filter((name) => ROWS.some((r) => r.p === name));
const DEFAULTS = [...asked, ...BY_VOLUME.filter((p) => !asked.includes(p))].slice(0, 3);

const REF = __REF__;

const SEGS = [{ k: 'OCR', label: 'Outside central' }, { k: 'RCR', label: 'Rest of central' },
              { k: 'CCR', label: 'Core central' }];
const SLOTS = ['First', 'Second', 'Third'];
const n = (v) => v.toLocaleString('en-SG');
---
'''

