"""Generate CondoCompare.astro with its dataset emitted mechanically from live.json."""
import io, json

rows = json.load(io.open('cmp_rows.json', encoding='utf-8'))
DATA = json.dumps(rows, separators=(',', ':'), ensure_ascii=False)

HEAD = '''---
// Compare up to three condominiums, side by side, on what the public record can actually say.
//
// ROWS is emitted mechanically from data/live.json in the sg-property-decision repo (URA
// PMI_Resi_Transaction resale medians per project, twelve months to August 2026; nearest MRT
// from LTA station exits; district size-band medians from the same feed). It is generated by
// scripts, not hand-typed, and the count, the district coverage and each project's standing
// against its district are all recomputed from ROWS so the prose cannot drift from the data.
//
// INCLUSION RULE, applied mechanically: a project appears only with at least 10 resales in the
// twelve months. Below that a median moves on one unusual unit, and a comparison tool offering a
// number resting on two sales is worse than one that declines to. 309 of about 1,135 condominiums
// clear it. That is a real bound on coverage, and the figure says so rather than implying the
// list is every condominium in Singapore.
//
// COLOUR MEANS SEGMENT AND NOTHING ELSE (VOICE.md C10), reusing the validated triple from
// DistrictYieldChart and DistrictSupplyChart so the property charts agree: light
// #2563EB/#B45309/#7C3AED. It marks which market segment a project sits in — a classification,
// never a verdict. No metric is coloured by whether it is "good": a shorter walk, a longer lease
// and a higher price are not virtues in common, and the point of a comparison is that the reader
// weighs them rather than us. Every column carries its project name and segment code, so meaning
// never rests on colour alone.
//
// DIRECTION IS STATED, NEVER IMPLIED. Each row says what its bar measures and which way it runs,
// because half of these have no better end. "Against its district" is the sharpest case: it is a
// position, not a discount or a markup, and a newer building, a higher floor or a shorter walk
// can each explain it.
//
// The default three are the highest-volume projects in the set, picked by the data rather than by
// us, precisely so the starting state is not an editorial choice.
const ASOF = 'August 2026';
const MIN_SALES = 10;
const TOTAL_PROJECTS = 1135;

interface Row { p: string; d: string; n: string; g: 'CCR' | 'RCR' | 'OCR'; psf: number; v: number;
  l: number | string; m: number; x: string; s: number; b: number; q: number }

const ROWS: Row[] = __DATA__;

const DISTRICTS = [...new Set(ROWS.map((r) => r.d))]
  .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)));
const BY_D = DISTRICTS.map((d) => ({
  d,
  name: ROWS.find((r) => r.d === d).n,
  items: ROWS.filter((r) => r.d === d).sort((a, b) => a.p.localeCompare(b.p)),
}));
const DEFAULTS = [...ROWS].sort((a, b) => b.v - a.v).slice(0, 3).map((r) => r.p);
const SEGS = [{ k: 'OCR', label: 'Outside central' }, { k: 'RCR', label: 'Rest of central' },
              { k: 'CCR', label: 'Core central' }];
const SLOTS = ['First', 'Second', 'Third'];
const n = (v) => v.toLocaleString('en-SG');
---
'''

BODY = r'''
<figure class="cc">
  <figcaption class="cc-cap">
    <h4>Compare three, on the public record</h4>
    <p>Median resale price, how often units change hands, lease left, the walk to a station, the
    size that actually trades, and where each sits against its own district.{' '}
    {n(ROWS.length)} condominiums across {DISTRICTS.length} districts, twelve months to {ASOF}.</p>
  </figcaption>

  <div class="cc-picks">
    {[0, 1, 2].map((i) => (
      <div class="cc-pick">
        <label for={`cc-s${i}`}>{SLOTS[i]}</label>
        <select id={`cc-s${i}`}>
          <option value="">&mdash; none &mdash;</option>
          {BY_D.map((grp) => (
            <optgroup label={`${grp.d} · ${grp.name}`}>
              {grp.items.map((r) => (
                <option value={r.p} selected={r.p === DEFAULTS[i]}>{r.p}</option>
              ))}
            </optgroup>
          ))}
        </select>
      </div>
    ))}
  </div>

  <div class="cc-legend">
    {SEGS.map((s) => (<span class="cc-lg"><i class={`cc-dot ${s.k}`}></i>{s.label}</span>))}
    <span class="cc-hint">colour marks market segment, nothing more</span>
  </div>

  <div class="cc-out" id="cc-out" aria-live="polite"></div>

  <p class="cc-say" id="cc-say"></p>

  <p class="cc-src">Computed by us from URA private resale transactions and LTA station-exit
  locations, twelve months to {ASOF}. <b>A project appears only if at least {MIN_SALES} units
  resold in that period</b> &mdash; {n(ROWS.length)} of about {n(TOTAL_PROJECTS)} condominiums clear
  that, so this is the liquid end of the market and not a full list. Every price is a <b>median of
  what traded</b>: it mixes floor, stack, facing, condition and renovation, so it is not a valuation
  of any particular unit, and two buildings can differ for reasons no public figure captures.
  Distances are straight-line to the nearest station entrance, so a real walk is typically
  20&ndash;40% further. &ldquo;Against its district&rdquo; compares a project with resale of the
  <b>same size band</b> in the same district. Nothing here ranks these buildings or recommends any
  of them.</p>
</figure>

<script is:inline define:vars={{ ROWS }}>
(function(){
const $ = id => document.getElementById(id);
const sgd = v => 'S$' + Math.round(v).toLocaleString('en-SG');
const num = v => Math.round(v).toLocaleString('en-SG');
const BY = Object.fromEntries(ROWS.map(r => [r.p, r]));

// Each metric states what it measures and which way its bar runs. `dir` is descriptive only and
// never styles anything, because none of these has a universally better end.
const METRICS = [
  { label: 'Median resale price', fmt: r => sgd(r.psf) + ' psf', val: r => r.psf,
    dir: 'longer bar = dearer per square foot' },
  { label: 'Against its district', val: r => Math.abs(r.psf / r.b - 1),
    fmt: r => { const g = (r.psf / r.b - 1) * 100;
                return (g >= 0 ? '+' : '\u2212') + Math.abs(g).toFixed(0) + '%'; },
    dir: 'vs same-size resale nearby \u2014 a position, not a discount' },
  { label: 'Resales in 12 months', fmt: r => num(r.v), val: r => r.v,
    dir: 'longer bar = units change hands more often' },
  { label: 'Lease remaining', fmt: r => r.l === 'FH' ? 'Freehold' : r.l + ' yrs',
    val: r => r.l === 'FH' ? 999 : Number(r.l), dir: 'longer bar = more years left' },
  { label: 'To the nearest MRT', fmt: r => num(r.m) + ' m \u00b7 ' + r.x, val: r => r.m,
    dir: 'longer bar = further away, straight line' },
  { label: 'Size that actually trades', fmt: r => num(r.s) + ' sq ft', val: r => r.s,
    dir: 'longer bar = larger median unit' },
  { label: 'Typical price paid', fmt: r => sgd(r.q), val: r => r.q,
    dir: 'longer bar = larger typical cheque' },
];

const esc = s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

function render(){
  const picked = [0,1,2].map(i => BY[$('cc-s'+i).value]).filter(Boolean);
  if (!picked.length){
    $('cc-out').innerHTML = '<p class="cc-empty">Choose at least one building to compare.</p>';
    $('cc-say').textContent = '';
    return;
  }
  let h = '<div class="cc-heads" style="--cols:' + picked.length + '">';
  picked.forEach(r => {
    h += '<div class="cc-head"><b>' + esc(r.p) + '</b><span class="cc-meta"><i class="cc-dot '
      + r.g + '"></i>' + r.d + ' \u00b7 ' + r.g + '</span></div>';
  });
  h += '</div>';

  METRICS.forEach(mt => {
    const vals = picked.map(mt.val);
    const max = Math.max.apply(null, vals.concat([1]));
    h += '<div class="cc-metric"><div class="cc-mlabel">' + mt.label + '<em>' + mt.dir
       + '</em></div><div class="cc-mrows" style="--cols:' + picked.length + '">';
    picked.forEach((r, i) => {
      h += '<div class="cc-cell"><span class="cc-v">' + esc(mt.fmt(r)) + '</span>'
        + '<span class="cc-track"><span class="cc-bar ' + r.g + '" style="width:'
        + Math.max(2, (vals[i] / max) * 100) + '%" role="img" aria-label="'
        + esc(r.p + ', ' + mt.label + ': ' + mt.fmt(r) + '.') + '"></span></span></div>';
    });
    h += '</div></div>';
  });
  $('cc-out').innerHTML = h;

  const dearest = picked.reduce((a,b) => b.psf > a.psf ? b : a);
  const liquid  = picked.reduce((a,b) => b.v > a.v ? b : a);
  $('cc-say').innerHTML = 'Of ' + (picked.length === 1 ? 'the one selected' : 'these ' + picked.length)
    + ', <b>' + esc(dearest.p) + '</b> carries the highest median price per square foot and <b>'
    + esc(liquid.p) + '</b> traded most often over the year. Those are two different questions and '
    + 'they need not point the same way. What none of these columns can tell you is which unit, on '
    + 'which floor, facing what \u2014 and that is usually the difference that decides a purchase.';
}

function init(){
  [0,1,2].forEach(i => $('cc-s'+i).addEventListener('change', render));
  render();
}
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
else init();
})();
</script>

<style is:global>
.cc{
  --cc-ocr:#2563EB; --cc-rcr:#B45309; --cc-ccr:#7C3AED;   /* validated triple, light card */
  --cc-ink:var(--color-dark); --cc-body:var(--color-body); --cc-muted:var(--color-muted);
  --cc-rule:var(--color-border); --cc-soft:#F0ECE2;
  --cc-mono:var(--font-mono),'SF Mono',Menlo,Consolas,monospace;
  margin:26px 0;padding:20px 22px 16px;background:#fff;
  border:1px solid var(--cc-rule);border-radius:12px
}
/* No dark-scheme override: the card is pinned white in both schemes, so the ink follows the card
   rather than the page, and the triple is the light-card variant for that reason. */
.post-content .cc-cap{margin:0 0 14px;padding:0;text-align:left}
.post-content .cc-cap h4{margin:0 0 3px;font-size:15.5px;font-weight:700;color:var(--cc-ink);
  font-family:var(--font-body);letter-spacing:0}
.post-content .cc-cap p{margin:0;font-size:12.5px;color:var(--cc-muted);line-height:1.5}

.cc-picks{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:12px}
.cc-pick label{display:block;font-size:11px;font-weight:700;text-transform:uppercase;
  letter-spacing:.05em;color:var(--cc-muted);margin-bottom:4px}
.cc select{width:100%;font-family:inherit;font-size:12.5px;color:var(--cc-ink);background:#fff;
  border:1px solid var(--cc-rule);border-radius:6px;padding:11px 8px;min-height:44px}
.cc select:focus-visible{outline:2px solid var(--cc-ink);outline-offset:2px}

.cc-legend{display:flex;flex-wrap:wrap;gap:6px 16px;align-items:center;margin-bottom:12px;font-size:11.5px}
.cc-lg{display:flex;align-items:center;gap:6px;color:var(--cc-body)}
.cc-dot{width:9px;height:9px;border-radius:50%;display:inline-block;flex:0 0 auto}
.cc-dot.OCR{background:var(--cc-ocr)} .cc-dot.RCR{background:var(--cc-rcr)} .cc-dot.CCR{background:var(--cc-ccr)}
.cc-hint{color:var(--cc-muted);font-style:italic}

.cc-heads,.cc-mrows{display:grid;grid-template-columns:repeat(var(--cols),1fr);gap:10px}
.cc-heads{padding-bottom:8px;border-bottom:1px solid var(--cc-rule);margin-bottom:10px}
.cc-head b{display:block;font-size:13px;color:var(--cc-ink);line-height:1.25}
.cc-meta{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--cc-muted);margin-top:2px}

.cc-metric{margin-bottom:11px}
.cc-mlabel{font-size:11.5px;font-weight:600;color:var(--cc-body);margin-bottom:5px}
.cc-mlabel em{display:block;font-style:normal;font-weight:400;font-size:11px;color:var(--cc-muted)}
.cc-cell{min-width:0}
.cc-v{display:block;font-family:var(--cc-mono);font-variant-numeric:tabular-nums;font-size:12px;
  font-weight:600;color:var(--cc-ink);margin-bottom:3px;white-space:nowrap;overflow:hidden;
  text-overflow:ellipsis}
.cc-track{display:block;height:9px;background:var(--cc-soft);border-radius:3px}
.cc-bar{display:block;height:9px;border-radius:3px;min-width:2px}
.cc-bar.OCR{background:var(--cc-ocr)} .cc-bar.RCR{background:var(--cc-rcr)} .cc-bar.CCR{background:var(--cc-ccr)}
.post-content p.cc-empty{margin:0;font-size:12.5px;color:var(--cc-muted)}

.post-content p.cc-say{margin:14px 0 0;padding-top:12px;border-top:1px solid var(--cc-rule);
  font-size:12.5px;line-height:1.6;color:var(--cc-body)}
.post-content p.cc-src{margin:10px 0 0;padding-top:10px;border-top:1px solid var(--cc-rule);
  font-size:11.5px;line-height:1.55;color:var(--cc-muted)}

@media (max-width:640px){
  .cc{padding:16px 14px 13px}
  .cc-picks{grid-template-columns:1fr;gap:8px}
  .cc-hint{display:none}
  .cc-head b{font-size:12px}
  /* Three columns on a phone leave ~102px each, which truncates the longest value
     ("388 m · Queenstown") and eats the station name — the useful half. Let values wrap
     instead of ellipsing; uneven cell heights are harmless because each metric is its
     own block. Measured at a real 390px viewport. */
  .cc-v{font-size:11px;white-space:normal;overflow:visible;text-overflow:clip;line-height:1.3}
  .cc-mlabel{font-size:11px}
  .cc-mlabel em{font-size:11px}
}
</style>
'''

out = HEAD.replace('__DATA__', DATA) + BODY
path = r'C:\TheEnoughPoint-wt-newlaunch\src\components\CondoCompare.astro'
io.open(path, 'w', encoding='utf-8').write(out)
print('written', len(out), 'bytes ·', len(rows), 'projects ·', len({r['d'] for r in rows}), 'districts')
