"""Generate BreakEven.astro — the hurdle table.

Two reasons this stopped being a markdown table in the article.

Every cell is a function of one live number, the exit comparable. Fifteen typed figures behind a
guard is worse than fifteen computed ones with no guard needed: check_figures.py could only tell
us the article had drifted, never stop it drifting.

And markdown cannot express what the table means. The four annualised columns are one idea, not
four, and they are a different KIND of number from the total rise — the total needs no view on how
long anyone holds, the rates do. A flat six-column grid states them as peers. A spanning header and
a rule between the two blocks says which is the answer and which is the restatement.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from feed_guard import load_live  # noqa: E402
from jsx_space_lint import assert_clean  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
LIVE = os.environ.get('LIVE_JSON', r'C:/dev/sg-property-decision/data/live.json')

PRICES = (2600, 2900, 3100)
HORIZONS = (7, 9, 12, 15)
ROUND_TRIP = 1.06          # stamp duty in, agent commission out
LEASE_MIN, VOL_MIN = 85, 10

data, provenance = load_live(LIVE, ['projects', 'districts'])

# The same five buildings check_figures.py recomputes, by the same rule: District 20, leasehold
# with 85+ years, at least ten resales in the period.
comps = [r for r in data['projects']['rows']
         if r['district'] == 'D20' and r['lease'] not in ('FH', None)
         and int(r['lease']) >= LEASE_MIN and r['vol_12m'] >= VOL_MIN]
comps.sort(key=lambda r: r['median_psf'])
BASE = comps[len(comps) // 2]['median_psf']

rows = []
for p in PRICES:
    need = p * ROUND_TRIP / BASE
    rows.append({
        'psf': p,
        'rise': round((need - 1) * 100),
        'rates': [round((need ** (1 / n) - 1) * 100, 1) for n in HORIZONS],
    })
MAX_RISE = max(r['rise'] for r in rows)

# The base is the median of a five-building set, which means it IS one building — Thomson Three,
# on 22 sales. Two other defensible estimators of the same set give a different answer, and the
# reader was being shown a point where the honest object is a range. The article's own thesis is
# that whoever picks the window picks the answer; picking one estimator in silence is that same
# error a level down, so the spread is computed and stated rather than left for someone to find.
psfs = [r['median_psf'] for r in comps]
vols = [r['vol_12m'] for r in comps]
EST = {
    'median of their medians': sorted(psfs)[len(psfs) // 2],
    'mean of them': sum(psfs) / len(psfs),
    'weighted by resale count': sum(p * v for p, v in zip(psfs, vols)) / sum(vols),
}
MID = PRICES[len(PRICES) // 2]
EST_RISE = sorted(round((MID * ROUND_TRIP / b - 1) * 100) for b in EST.values())
EST_LINE = ' · '.join(f'{k} S${b:,.0f}' for k, b in EST.items())

hdr_years = ''.join(
    f'<th scope="col">{n}<span class="be-u">yrs</span></th>' for n in HORIZONS)

body = ''
for r in rows:
    cells = ''.join(
        f'<td class="be-r{" be-first" if i == 0 else ""}">{v:.1f}<span class="be-pc">%</span></td>'
        for i, v in enumerate(r['rates']))
    body += (
        '    <tr>\n'
        f'      <th scope="row">S${r["psf"]:,}<span class="be-u">psf</span></th>\n'
        '      <td class="be-key">\n'
        f'        <span class="be-num">+{r["rise"]}<span class="be-pc">%</span></span>\n'
        # Reserve the cell padding inside the calc. As a bare percentage the longest bar ran 10px
        # past the cell, and clamping it with max-width instead broke proportionality — the lengths
        # stopped matching the values they encode, which is the one thing a bar must not do.
        f'        <span class="be-bar" style="width:calc((100% - 20px) * '
        f'{r["rise"] / MAX_RISE:.4f})"></span>\n'
        '      </td>\n'
        f'{cells and "      " + cells}\n'
        '    </tr>\n')

OUT = f'''---
// GENERATED by scripts/gen_breakeven.py — do not edit. Regenerate to change.
// Data: {provenance}
//
// The exit comparable is recomputed here from the feed, by the same rule check_figures.py uses:
// District 20, leasehold, {LEASE_MIN}+ years remaining, {VOL_MIN}+ resales in the period, median of their
// median $psf. It is S${BASE:,} on this snapshot, and every figure below follows from it.
const BASE = {BASE};
---

<figure class="be">
  <table>
    <colgroup>
      <col /><col class="be-c-key" /><col span="{len(HORIZONS)}" />
    </colgroup>
    <thead>
      <tr class="be-hg">
        <td></td><td></td>
        <th scope="colgroup" colspan="{len(HORIZONS)}">Annual rate, if you sell after</th>
      </tr>
      <tr class="be-hc">
        <th scope="col">If you pay</th>
        <th scope="col" class="be-c-key">District 20 must rise</th>
        {hdr_years}
      </tr>
    </thead>
    <tbody>
{body}    </tbody>
  </table>
  <p class="be-note">The exit base is <b>S${BASE:,}</b>, from {len(comps)} District 20 buildings with
  {LEASE_MIN}+ years of lease and at least {VOL_MIN} resales — {sum(r['vol_12m'] for r in comps)} sales in all.
  Which average you take moves the answer: {EST_LINE}. On the middle row that is a spread of{{' '}}
  <b>+{EST_RISE[0]}% to +{EST_RISE[-1]}%</b>, so read the column as about that wide, not as a point. Five
  buildings is a thin set, and the median of five is really one of them.</p>
</figure>

<style is:global>
.post-content figure.be{{margin:22px 0;padding:0;overflow-x:auto}}
.post-content figure.be table{{width:100%;min-width:430px;margin:0;border-collapse:collapse;
  display:table;white-space:nowrap;font-variant-numeric:tabular-nums;
  font-feature-settings:"tnum" 1}}

/* Two header rows: the span says the four columns are one idea, and the second row carries only
   the numbers. "IN 7 YEARS / IN 9 / IN 12 / IN 15" said the unit once and then dropped it. */
.post-content figure.be .be-hg th{{padding:0 10px 3px;border:0;background:transparent;
  text-align:center;font-size:11px;font-weight:700;letter-spacing:.07em;text-transform:uppercase;
  color:#6b7a8d;border-bottom:1px solid #dde3ea}}
.post-content figure.be .be-hg td{{border:0;background:transparent;padding:0}}
.post-content figure.be .be-hc th{{padding:8px 10px;border:0;border-bottom:1.5px solid #0b1d33;
  background:transparent;text-align:right;font-size:11px;font-weight:700;letter-spacing:.05em;
  text-transform:uppercase;color:#6b7a8d;white-space:nowrap;vertical-align:bottom}}
.post-content figure.be .be-hc th:first-child{{text-align:left}}

.post-content figure.be tbody tr{{background:transparent}}
.post-content figure.be tbody th{{padding:11px 10px;border:0;border-bottom:1px solid #eef1f5;
  background:transparent;text-align:left;font-size:13px;font-weight:600;color:#0b1d33;
  white-space:nowrap}}
.post-content figure.be tbody td{{padding:11px 10px;border:0;border-bottom:1px solid #eef1f5;
  background:transparent;text-align:right;font-size:13px;color:#33465e}}
.post-content figure.be tbody tr:last-child th,
.post-content figure.be tbody tr:last-child td{{border-bottom:0}}

/* The answer column. Larger, darker, and separated from the restatement by a rule — the total
   rise needs no view on the hold, the rates do, so they are not peers. */
.post-content figure.be .be-key{{position:relative;text-align:left;padding-bottom:15px}}
.post-content figure.be .be-num{{font-size:19px;font-weight:700;color:#0b1d33;letter-spacing:-.01em}}
.post-content figure.be .be-bar{{position:absolute;left:10px;bottom:8px;height:3px;border-radius:2px;
  background:#2a78d6}}
.post-content figure.be .be-first{{border-left:1px solid #dde3ea}}
.post-content figure.be .be-hc th.be-c-key{{text-align:left}}

/* The unit, said once per number and never competing with it. */
.post-content figure.be .be-u{{margin-left:4px;font-size:11px;font-weight:400;color:#8a97a8;
  letter-spacing:.02em;text-transform:none}}
.post-content figure.be .be-pc{{font-size:11px;font-weight:600;margin-left:1px}}
.post-content figure.be .be-num .be-pc{{font-size:13.5px}}
.post-content figure.be .be-note{{margin:12px 2px 0;font-size:12.5px;line-height:1.55;color:#5b6b7f}}
.post-content figure.be .be-note b{{color:#0b1d33;font-weight:700}}

@media (max-width: 640px){{
  /* The site rule turns every .post-content table into its own scroll box. This one already
     scrolls at the figure, and doing it twice puts the header span out of register with the
     columns it spans. */
  .post-content figure.be table{{display:table;overflow-x:visible}}
  .post-content figure.be tbody th,
  .post-content figure.be tbody td{{padding:10px 8px}}
  .post-content figure.be .be-num{{font-size:17px}}
}}
</style>
'''

assert_clean(OUT, 'BreakEven.astro')
path = os.path.join(HERE, '..', 'src', 'components', 'BreakEven.astro')
io.open(path, 'w', encoding='utf-8').write(OUT)
print(f'written {len(OUT)} bytes · exit comparable S${BASE:,} from {len(comps)} buildings')
print('rows:', ', '.join(f'{r["psf"]}→+{r["rise"]}%' for r in rows))
print('provenance:', provenance)
