"""Generate CondoCompare.astro with its dataset emitted mechanically from live.json."""
import io, json

rows = json.load(io.open('cmp_rows.json', encoding='utf-8'))
DATA = json.dumps(rows, separators=(',', ':'), ensure_ascii=False)

HEAD = '''---
// Compare up to three condominiums, side by side, on what the public record can actually say.
//
// ROWS is emitted mechanically from data/live.json in the sg-property-decision repo (URA
// PMI_Resi_Transaction resale medians per project, twelve months to August 2026; nearest MRT from
// LTA station exits; district size-band medians from the same feed). Generated by
// scripts/gen_condo_compare.py, never hand-typed; the count, the district coverage and every
// derived figure are recomputed from ROWS so prose cannot drift from bars.
//
// INCLUSION RULE, mechanical and stated on the figure: at least 10 resales in the twelve months.
// 309 of about 1,135 condominiums clear it. Below that a median moves on one unusual unit, and a
// comparison offering a number resting on two sales is worse than one that declines to.
//
// WHICH ONE IS AHEAD, AND BY HOW MUCH — the point of the redesign. Bars alone made the reader
// eyeball three lengths and guess the margin. Every cell now carries an explicit delta, and each
// measure declares whether it even HAS a better end:
//
//   more  — longer lease, more resales. More is unambiguously more of the thing.
//   less  — distance to a station. Nearer is unambiguously nearer.
//   none  — price psf, standing vs district, unit size, typical quantum. These have NO better
//           end: cheaper suits a buyer and dearer is what the market pays; a big flat is right
//           for one household and wrong for the next. For these the tool reports the spread and
//           refuses to name a leader, because doing so would be inventing a preference.
//
// There is deliberately NO composite score. Summing these into a winner would be a ranked league
// table, which the venture's red lines prohibit and which would be dishonest anyway — the weights
// are the reader's and nobody else's. The figure says so in as many words.
//
// COLOUR SHOWS RELATIVE STANDING WITHIN EACH ROW — never who the building is.
//
// Two earlier attempts were both wrong, and the second failed in a way worth recording.
//
// First it marked market segment, which the article's own default exposed: three District 20
// buildings are all RCR, so all three bars came out identical and the channel carried nothing.
//
// Then it identified the building — one hue per column, blue/orange/aqua. That answered "which
// column is which" but introduced a fairness problem: those hues are not emotionally neutral. The
// building that happened to be picked third got the green one. Nobody chose that, and no reader
// can un-see it. A comparison tool that hands out a favourable tone by slot order is putting a
// thumb on the scale by accident, which is worse than doing it on purpose.
//
// So colour now encodes RANK WITHIN THE ROW, on a single hue, and no project owns a tone. A
// building that leads on lease and trails on price is dark on one row and light on the next —
// which is the honest picture. Identity is carried by the column header, which never moves.
//
//   ranked rows    one blue ordinal ramp: darkest leads, lightest trails.
//   unranked rows  a flat neutral grey on all three, because "strength" is undefined for price,
//                  standing-vs-district, unit size and typical quantum. Colouring those would
//                  invent the preference the tool explicitly refuses to hold.
//
// Palette, validated rather than eyeballed. Ordinal ramp #86b6ef / #3987e5 / #1c5cab checked with
// --ordinal: lightness monotone PASS, adjacent delta-L PASS, light-end contrast 2.11:1 against
// the 2:1 ordinal floor PASS, single hue (3 degrees spread) PASS. The unranked neutral #6b7280
// was then checked AGAINST the ramp, because both appear in one figure: normal-vision deltaE 22.6
// and deutan 21.8 against the lightest step, so the "no ranking here" grey cannot be mistaken for
// a ramp step. An earlier candidate sat at deltaE 13.7 and was rejected on that test.
//
// Leadership is still ALSO marked by a text tag and an explicit delta, so the ranking survives
// greyscale, colour blindness and a monochrome print — colour is reinforcement here, never the
// only carrier.
//
// The class prefix is `cmp-`, not `cc-`: src/pages/cashback-calendar.astro already owns `cc-` and
// both files ship `is:global` styles, so sharing a prefix would collide the moment they met.
const ASOF = 'August 2026';
const MIN_SALES = 10;
const TOTAL_PROJECTS = 1135;

interface Row { p: string; d: string; n: string; g: 'CCR' | 'RCR' | 'OCR'; psf: number; v: number;
  l: number | string; m: number; x: string; s: number; b: number; q: number }

const ROWS: Row[] = __DATA__;

const DISTRICTS = [...new Set(ROWS.map((r) => r.d))]
  .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)));
const BY_D = DISTRICTS.map((d) => ({
  d,
  name: ROWS.find((r) => r.d === d).n,
  items: ROWS.filter((r) => r.d === d).sort((a, b) => a.p.localeCompare(b.p)),
}));

// The opening three. Callers may pass their own via the `defaults` prop — an article about one
// project wants its own neighbourhood, the standalone page wants no local bias — but a name that
// is not in ROWS is dropped rather than silently rendering an empty column, and the data's own
// answer (most traded) fills any gap.
interface Props { defaults?: string[] }
const BY_VOLUME = [...ROWS].sort((a, b) => b.v - a.v).map((r) => r.p);
const asked = (Astro.props.defaults ?? []).filter((name) => ROWS.some((r) => r.p === name));
const DEFAULTS = [...asked, ...BY_VOLUME.filter((p) => !asked.includes(p))].slice(0, 3);

const SEGS = [{ k: 'OCR', label: 'Outside central' }, { k: 'RCR', label: 'Rest of central' },
              { k: 'CCR', label: 'Core central' }];
const SLOTS = ['First', 'Second', 'Third'];
const n = (v) => v.toLocaleString('en-SG');
---
'''

BODY = r'''
<figure class="cmp">
  <figcaption class="cmp-cap">
    <h4>Compare three, on the public record</h4>
    <p>Seven measures, {n(ROWS.length)} condominiums, {DISTRICTS.length} districts, twelve months
    to {ASOF}. Three of the seven have a better end and are marked with it. Four do not, and say so.</p>
  </figcaption>

  <div class="cmp-picks">
    {[0, 1, 2].map((i) => (
      <div class="cmp-pick">
        <label for={`cmp-s${i}`}>{SLOTS[i]}</label>
        <select id={`cmp-s${i}`}>
          <option value="">&mdash; none &mdash;</option>
          {BY_D.map((grp) => (
            <optgroup label={`${grp.d} · ${grp.name}`}>
              {grp.items.map((r) => (
                <option value={r.p} selected={r.p === DEFAULTS[i]}>{r.p}</option>
              ))}
            </optgroup>
          ))}
        </select>
      </div>
    ))}
  </div>

  <div class="cmp-legend">
    <span class="cmp-scale">
      <i class="cmp-key r3"></i><i class="cmp-key r2"></i><i class="cmp-key r1"></i>
      darker leads this row, lighter trails
    </span>
    <span class="cmp-scale"><i class="cmp-key n"></i>no better end &mdash; not ranked</span>
    <span class="cmp-hint">Colour shows standing <em>within a row</em>, never which building it is
    &mdash; so no project owns a shade, and one that leads on lease can trail on price.</span>
  </div>

  <div class="cmp-lead" id="cmp-lead" aria-live="polite"></div>

  <details class="cmp-fold">
    <summary>All seven measures, side by side</summary>
    <div class="cmp-out" id="cmp-out"></div>
  </details>

  <p class="cmp-say" id="cmp-say"></p>

  <p class="cmp-src">Computed by us from URA private resale transactions and LTA station-exit
  locations, twelve months to {ASOF}. <b>A project appears only if at least {MIN_SALES} units
  resold in that period</b> &mdash; {n(ROWS.length)} of about {n(TOTAL_PROJECTS)} condominiums clear
  that, so this is the liquid end of the market, not a full list. Every price is a <b>median of what
  traded</b>, mixing floor, stack, facing, condition and renovation, so it is not a valuation of any
  particular unit. Distances are straight-line to the nearest station entrance; a real walk is
  typically 20&ndash;40% further. &ldquo;Against its district&rdquo; compares a project with resale
  of the <b>same size band</b> in the same district &mdash; a position, not a discount, which a
  newer building, a higher floor or a shorter walk can each explain. Buildings are labelled by
  postal district, which is exact. We do not show a market-segment tag: the upstream
  classification is an approximation and disagrees with itself inside some districts. <b>There is no overall score
  and there will not be one</b>: the weights belong to whoever is buying.</p>
</figure>

<script is:inline define:vars={{ ROWS }}>
(function(){
const $ = id => document.getElementById(id);
const sgd = v => 'S$' + Math.round(v).toLocaleString('en-SG');
const num = v => Math.round(v).toLocaleString('en-SG');
const BY = Object.fromEntries(ROWS.map(r => [r.p, r]));
const esc = s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

// `dir` is the honest part. 'more'/'less' name a direction the data genuinely has; 'none' means
// the measure has no better end and the tool must not invent one. `lead` is the word used for the
// front-runner — factual ("longest lease"), never evaluative ("best").
// `short` is the summary's wording, `brief` formats a value compactly for it, and `kind` says how
// to measure the spread between buildings \u2014 a ratio for counts and money, percentage points for
// the one measure that is already a percentage.
const METRICS = [
  { label: 'Median resale price', short: 'price per square foot', dir: 'none', lead: '', kind: 'ratio',
    fmt: r => sgd(r.psf) + ' psf', brief: r => sgd(r.psf), val: r => r.psf,
    delta: (v, ref) => pctDelta(v, ref),
    note: 'no better end \u2014 cheaper suits a buyer, dearer is what the market pays' },
  { label: 'Against its district', short: 'standing vs its district', dir: 'none', lead: '', kind: 'pp',
    fmt: r => signed((r.psf / r.b - 1) * 100) + '%', brief: r => signed((r.psf / r.b - 1) * 100) + '%',
    val: r => r.psf / r.b - 1,
    delta: (v, ref) => ppDelta(v * 100, ref * 100),
    note: 'no better end \u2014 a position vs same-size resale nearby, not a discount' },
  { label: 'Resales in 12 months', short: 'how often units sell', dir: 'more', lead: 'most traded', kind: 'ratio',
    fmt: r => num(r.v), brief: r => num(r.v) + ' sales', val: r => r.v,
    delta: (v, ref) => absDelta(v, ref, ''),
    note: 'more changes of hand = easier to leave when you need to' },
  // `fh` marks the ONE measure that uses 999 as a freehold sentinel. Without it the spread and
  // phrase helpers treated any value over 999 as freehold — which is every price and every floor
  // area — and silently scored them as zero spread. That reported a 2.2x price gap between
  // Braddell View and Jadescape as "much the same". Caught by reading the summary against the
  // detail grid rather than trusting it.
  { label: 'Lease remaining', short: 'lease left', dir: 'more', lead: 'longest', kind: 'ratio', fh: true,
    fmt: r => r.l === 'FH' ? 'Freehold' : r.l + ' yrs',
    brief: r => r.l === 'FH' ? 'freehold' : r.l + ' yrs',
    val: r => r.l === 'FH' ? 999 : Number(r.l),
    delta: (v, ref) => (v >= 999 || ref >= 999) ? ''
      : absDelta(v, ref, Math.abs(v - ref) === 1 ? ' yr' : ' yrs'),
    note: 'more years is more, and under 60 the CPF and lending rules tighten' },
  { label: 'To the nearest MRT', short: 'the walk to a station', dir: 'less', lead: 'nearest', kind: 'ratio',
    fmt: r => num(r.m) + ' m \u00b7 ' + r.x, brief: r => num(r.m) + ' m', val: r => r.m,
    delta: (v, ref) => absDelta(v, ref, ' m'),
    note: 'nearer is nearer \u2014 whether that beats quiet is yours to weigh' },
  { label: 'Size that actually trades', short: 'the size that trades', dir: 'none', lead: '', kind: 'ratio',
    fmt: r => num(r.s) + ' sq ft', brief: r => num(r.s) + ' sq ft', val: r => r.s,
    delta: (v, ref) => absDelta(v, ref, ' sq ft'),
    note: 'no better end \u2014 the right size is the one you need' },
  { label: 'Typical price paid', short: 'the typical cheque', dir: 'none', lead: '', kind: 'ratio',
    fmt: r => sgd(r.q), brief: r => sgd(r.q), val: r => r.q,
    delta: (v, ref) => pctDelta(v, ref),
    note: 'no better end \u2014 it tracks the size that trades as much as the price' },
];

// How far apart the selected buildings are on a measure, on a scale comparable across measures.
// A ratio measure uses max/min - 1; the percentage-point measure uses its range in points over a
// 20pp reference, so 5pp of spread reads like 25% and the two kinds can be ranked together.
function spreadOf(mt, picked){
  const vals = picked.map(mt.val);
  const hi = Math.max.apply(null, vals), lo = Math.min.apply(null, vals);
  if (mt.kind === 'pp') return Math.abs(hi - lo) * 100 / 20;
  if (mt.fh && hi >= 999) return 0;              // freehold in the set makes the ratio meaningless
  return lo > 0 ? (hi / lo) - 1 : 0;
}

// Plain-language size of the gap. "Nearly three times" beats "+195%" for a reader deciding
// whether a difference is worth caring about.
function gapPhrase(mt, picked){
  const vals = picked.map(mt.val);
  const hi = Math.max.apply(null, vals), lo = Math.min.apply(null, vals);
  if (mt.kind === 'pp') return Math.round(Math.abs(hi - lo) * 100) + ' points apart';
  if (mt.fh && hi >= 999) return 'one is freehold';
  const ratio = lo > 0 ? hi / lo : 0;
  if (ratio >= 1.8) return 'about ' + (Math.round(ratio * 10) / 10) + ' times';
  const pct = Math.round((ratio - 1) * 100);
  return pct + '% apart';
}

// A value that rounds to zero gets no sign: "\u22120%" reads as a bug, not as "level".
function signed(x){
  const r = Math.abs(x).toFixed(0);
  return r === '0' ? '0' : (x >= 0 ? '+' : '\u2212') + r;
}
function absDelta(v, ref, unit){
  const d = v - ref;
  if (Math.round(Math.abs(d)) === 0) return 'same';
  return signed(d) + unit;
}
function pctDelta(v, ref){
  if (!ref) return '';
  const d = (v / ref - 1) * 100;
  if (Math.abs(d) < 0.5) return 'same';
  return signed(d) + '%';
}
function ppDelta(v, ref){
  const d = v - ref;
  if (Math.abs(d) < 0.5) return 'same';
  return signed(d) + ' pp';
}

// The summary that answers the question a reader actually arrives with: what is different here,
// and by how much? Seven rows of equal weight made them do that synthesis themselves. Measures are
// ranked by how far apart the selected buildings sit, the biggest three are stated in words, and
// everything the buildings agree on is collapsed to a single line — because "these are basically
// the same on lease and price" is itself the finding most of the time.
const CLOSE = 0.15;   // below 15% apart, the buildings are alike on that measure

function renderLead(picked){
  if (picked.length < 2){ $('cmp-lead').innerHTML = ''; return; }
  // Freehold against leasehold is a difference in KIND, not a percentage. The sentinel makes its
  // ratio meaningless, so the measure is set aside and named — it must not fall into "much the
  // same", which is what a zero spread would otherwise say about freehold versus 91 years.
  const mixedTenure = METRICS.filter(mt => mt.fh).filter(mt => {
    const v = picked.map(mt.val);
    return Math.max.apply(null, v) >= 999 && Math.min.apply(null, v) < 999;
  });
  const ranked = METRICS.filter(mt => !mixedTenure.includes(mt))
    .map(mt => ({ mt, s: spreadOf(mt, picked) })).sort((a, b) => b.s - a.s);
  // Every measure lands in exactly one of these three. An earlier version sliced the top three
  // and filtered the rest on `s < CLOSE`, so a measure that differed but ranked fourth appeared in
  // neither list and silently disappeared from the summary.
  const differing = ranked.filter(x => x.s >= CLOSE);
  const apart = differing.slice(0, 3);
  const alsoApart = differing.slice(3);
  const alike = ranked.filter(x => x.s < CLOSE);

  let h = '';
  if (apart.length){
    h += '<div class="cmp-leadh">Where they differ most</div><ul class="cmp-diffs">';
    apart.forEach(({ mt, s }) => {
      const vals = picked.map(mt.val);
      const hiV = Math.max.apply(null, vals), loV = Math.min.apply(null, vals);
      const hi = picked[vals.indexOf(hiV)], lo = picked[vals.indexOf(loV)];
      // On a ranked measure name the front-runner; on an unranked one just show the two ends, in
      // the order the data happens to give, so the sentence carries no preference.
      const front = mt.dir === 'more' ? hi : mt.dir === 'less' ? lo : null;
      const other = front === hi ? lo : hi;
      h += '<li><b>' + esc(mt.short) + '</b> &mdash; <span class="cmp-gap">' + gapPhrase(mt, picked)
        + '</span><br>'
        + (front
            ? esc(front.p) + ' ' + esc(mt.brief(front)) + ' <em>(' + mt.lead + ')</em>, '
              + esc(other.p) + ' ' + esc(mt.brief(other))
            : esc(hi.p) + ' ' + esc(mt.brief(hi)) + ', ' + esc(lo.p) + ' ' + esc(mt.brief(lo)))
        + '</li>';
    });
    h += '</ul>';
  }
  if (mixedTenure.length){
    const fhNames = picked.filter(r => r.l === 'FH').map(r => esc(r.p));
    const lhNames = picked.filter(r => r.l !== 'FH').map(r => esc(r.p) + ' ' + r.l + ' yrs');
    h += '<p class="cmp-alike"><b>Different in kind, not degree</b> &mdash; '
      + fhNames.join(' and ') + (fhNames.length > 1 ? ' are freehold' : ' is freehold')
      + '; ' + lhNames.join(', ') + '. That is not a percentage gap and we do not state one.</p>';
  }
  if (alsoApart.length){
    h += '<p class="cmp-alike"><b>Also apart on</b> '
      + alsoApart.map(x => esc(x.mt.short) + ' (' + gapPhrase(x.mt, picked) + ')').join(' &middot; ')
      + '.</p>';
  }
  if (alike.length){
    h += '<p class="cmp-alike"><b>Much the same on</b> '
      + alike.map(x => esc(x.mt.short)).join(' &middot; ')
      + '. Where buildings agree, the measure is not the deciding one.</p>';
  }
  if (!apart.length){
    h = '<div class="cmp-leadh">These are close on everything measured here</div>'
      + '<p class="cmp-alike">No measure separates them by more than ' + Math.round(CLOSE * 100)
      + '%. Whatever decides between them is not in the public record &mdash; it is the unit, the '
      + 'floor and the outlook.</p>';
  }
  $('cmp-lead').innerHTML = h;
}

function render(){
  const picked = [0,1,2].map(i => BY[$('cmp-s'+i).value]).filter(Boolean);
  if (!picked.length){
    $('cmp-out').innerHTML = '<p class="cmp-empty">Choose at least one building to compare.</p>';
    $('cmp-say').textContent = '';
    return;
  }
  const cols = picked.length;
  let h = '<div class="cmp-heads" style="--cols:' + cols + '">';
  picked.forEach((r, i) => {
    h += '<div class="cmp-head"><b>' + esc(r.p)
      + '</b><span class="cmp-meta">' + r.d + ' \u00b7 ' + esc(r.n) + '</span></div>';
  });
  h += '</div>';

  METRICS.forEach(mt => {
    const vals = picked.map(mt.val);
    const max = Math.max.apply(null, vals);
    const min = Math.min.apply(null, vals);
    // Reference for the delta: the leader where one exists, otherwise the lowest value, so the
    // column reads as "how far from the front" or "how far above the cheapest".
    const isLead = i => cols > 1 && mt.dir !== 'none'
      && (mt.dir === 'more' ? vals[i] === max : vals[i] === min);
    const ref = mt.dir === 'more' ? max : mt.dir === 'less' ? min : min;
    const refLabel = mt.dir === 'none' ? 'vs lowest here' : 'from the front';
    // Bars stay proportional to the value, never to the gap: exaggerating a small spread to fill
    // the track would make two near-identical buildings look far apart.
    const scale = max || 1;
    // Rank within the row, on distinct values so ties share a step. Index 0 is the leading value
    // and takes the darkest step; unranked measures return the neutral.
    const ordered = mt.dir === 'none' ? null
      : [...new Set(vals)].sort((a, b) => mt.dir === 'more' ? b - a : a - b);
    const stepOf = (v) => {
      if (!ordered) return 'n';
      const ladder = ordered.length <= 1 ? ['r3'] : ordered.length === 2 ? ['r3','r1'] : ['r3','r2','r1'];
      return ladder[Math.min(ordered.indexOf(v), ladder.length - 1)];
    };

    h += '<div class="cmp-metric"><div class="cmp-mlabel">' + mt.label
       + (mt.dir === 'none' ? '<span class="cmp-tag cmp-tag-n">no better end</span>' : '')
       + '<em>' + mt.note + '</em></div>'
       + '<div class="cmp-mrows" style="--cols:' + cols + '">';
    picked.forEach((r, i) => {
      const lead = isLead(i);
      // On a measure with no better end the reference cell is simply the lowest of the three,
      // and saying "same" about a value compared with itself reads as a bug. Name it instead.
      const isRef = mt.dir === 'none' && vals[i] === ref;
      const d = cols > 1 && !lead
        ? (isRef ? (cols > 1 ? 'lowest here' : '') : mt.delta(vals[i], ref))
        : '';
      h += '<div class="cmp-cell' + (lead ? ' is-lead' : '') + '"><span class="cmp-v">'
        + esc(mt.fmt(r)) + '</span>'
        + '<span class="cmp-track"><span class="cmp-bar ' + stepOf(vals[i]) + '" style="width:'
        + Math.max(2, (vals[i] / scale) * 100) + '%" role="img" aria-label="'
        + esc(r.p + ', ' + mt.label + ': ' + mt.fmt(r) + (lead ? ', ' + mt.lead : '')
              + (d ? ', ' + d + ' ' + refLabel : '') + '.') + '"></span></span>'
        + (lead ? '<span class="cmp-delta cmp-best">\u25B2 ' + mt.lead + '</span>'
                : d ? '<span class="cmp-delta">' + d + '</span>' : '<span class="cmp-delta"></span>')
        + '</div>';
    });
    h += '</div></div>';
  });
  $('cmp-out').innerHTML = h;
  // The legend is static markup now: it describes the ramp, not the selection, because colour no
  // longer names anybody. Nothing to re-render.
  renderLead(picked);

  if (cols < 2){
    $('cmp-say').innerHTML = 'Add a second building and every row will show how far apart they are.';
    return;
  }
  // Count leads only across the measures that HAVE a direction. This is a tally, not a score:
  // it is never summed with the four that do not, and it is stated as such.
  const dirMetrics = METRICS.filter(m => m.dir !== 'none');
  const tally = picked.map(r => dirMetrics.filter(mt => {
    const vals = picked.map(mt.val);
    const v = mt.val(r);
    return mt.dir === 'more' ? v === Math.max.apply(null, vals) : v === Math.min.apply(null, vals);
  }).length);
  const parts = picked.map((r, i) => '<b>' + esc(r.p) + '</b> ' + tally[i]);
  $('cmp-say').innerHTML = 'On the ' + dirMetrics.length + ' measures that have a better end '
    + '(lease, liquidity, distance), the count runs ' + parts.join(' &middot; ') + '. '
    + 'The other four have no better end, so they are reported and not scored &mdash; and the three '
    + 'that do are not worth the same to everyone, which is why this tool will not add them up for '
    + 'you. What none of it can tell you is which unit, on which floor, facing what, and that is '
    + 'usually the difference that decides a purchase.';
}

function init(){
  [0,1,2].forEach(i => $('cmp-s'+i).addEventListener('change', render));
  render();
}
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
else init();
})();
</script>

<style is:global>
.cmp{
  /* One ordinal blue ramp — darkest leads its row, lightest trails. Validated with --ordinal
     against a #fff surface: monotone lightness, visible step gaps, light end 2.11:1 over the 2:1
     ordinal floor, hue spread 3 degrees. Plus one neutral for rows that cannot be ranked, checked
     against the ramp at normal-vision deltaE 22.6 so it can never read as a step. */
  --cmp-r3:#1c5cab; --cmp-r2:#3987e5; --cmp-r1:#86b6ef; --cmp-n:#6b7280;
  --cmp-ink:var(--color-dark); --cmp-body:var(--color-body); --cmp-muted:var(--color-muted);
  --cmp-rule:var(--color-border); --cmp-soft:#F0ECE2;
  --cmp-mono:var(--font-mono),'SF Mono',Menlo,Consolas,monospace;
  margin:26px 0;padding:20px 22px 16px;background:#fff;
  border:1px solid var(--cmp-rule);border-radius:12px
}
/* No dark-scheme override: the card is pinned white in both schemes, so the ink follows the card
   rather than the page, and the triple is the light-card variant for that reason. */
.post-content .cmp-cap{margin:0 0 14px;padding:0;text-align:left}
.post-content .cmp-cap h4{margin:0 0 3px;font-size:15.5px;font-weight:700;color:var(--cmp-ink);
  font-family:var(--font-body);letter-spacing:0}
.post-content .cmp-cap p{margin:0;font-size:12.5px;color:var(--cmp-muted);line-height:1.5}

.cmp-picks{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:12px}
.cmp-pick label{display:flex;align-items:center;font-size:11px;font-weight:700;
  text-transform:uppercase;letter-spacing:.05em;color:var(--cmp-muted);margin-bottom:4px}
.cmp select{width:100%;font-family:inherit;font-size:12.5px;color:var(--cmp-ink);background:#fff;
  border:1px solid var(--cmp-rule);border-radius:6px;padding:11px 8px;min-height:44px}
.cmp select:focus-visible{outline:2px solid var(--cmp-ink);outline-offset:2px}

.cmp-legend{display:flex;flex-wrap:wrap;gap:5px 16px;align-items:center;margin-bottom:12px;font-size:11.5px}
.cmp-lg{display:flex;align-items:center;gap:6px;color:var(--cmp-body)}
.cmp-key{width:10px;height:10px;border-radius:3px;display:inline-block;flex:0 0 auto;
  margin-right:6px;vertical-align:-1px}
.cmp-key.r3{background:var(--cmp-r3)} .cmp-key.r2{background:var(--cmp-r2)}
.cmp-key.r1{background:var(--cmp-r1)} .cmp-key.n{background:var(--cmp-n)}
.cmp-scale{display:flex;align-items:center;color:var(--cmp-body)}
.cmp-scale .cmp-key{margin-right:2px}
.cmp-scale .cmp-key:last-of-type{margin-right:6px}
.cmp-hint{color:var(--cmp-muted);flex-basis:100%}

.cmp-heads,.cmp-mrows{display:grid;grid-template-columns:repeat(var(--cols),1fr);gap:10px}
.cmp-heads{padding-bottom:8px;border-bottom:1px solid var(--cmp-rule);margin-bottom:10px}
.cmp-head b{display:block;font-size:13px;color:var(--cmp-ink);line-height:1.25}
.cmp-head .cmp-key{margin-right:5px}
.cmp-meta{display:flex;align-items:center;gap:5px;font-size:11px;color:var(--cmp-muted);margin-top:2px}

.cmp-metric{margin-bottom:13px}
.cmp-mlabel{font-size:11.5px;font-weight:600;color:var(--cmp-body);margin-bottom:5px}
.cmp-mlabel em{display:block;font-style:normal;font-weight:400;font-size:11px;color:var(--cmp-muted)}
.cmp-tag{display:inline-block;margin-left:6px;font-size:11px;font-weight:600;letter-spacing:.01em;
  border:1px solid var(--cmp-rule);border-radius:999px;padding:0 7px;color:var(--cmp-muted)}
.cmp-cell{min-width:0}
/* Emphasis, not valence. The leading value takes full ink and weight; the others step back one
   notch. This is the "highlight one, recede the rest" move — it sharpens the hierarchy a reader
   asked for without a green that would assert the leader is GOOD. Three of these seven measures
   have a direction; none of them has a virtue. Longest lease is not better than nearest station,
   and the tool's own copy says whether nearness beats quiet is the reader's to weigh. Status
   colour is reserved for things that genuinely mean good or bad, and naming a winner among named
   developments is the one thing this tool must never do. */
.cmp-v{display:block;font-family:var(--cmp-mono);font-variant-numeric:tabular-nums;font-size:12px;
  font-weight:500;color:var(--cmp-body);margin-bottom:3px}
.cmp-cell.is-lead .cmp-v{font-weight:700;color:var(--cmp-ink)}
.cmp-track{display:block;height:10px;background:var(--cmp-soft);border-radius:0 4px 4px 0}
/* 4px rounded data-end, thin mark, no border — separation comes from the 10px grid gap
   between cells rather than a stroke around each bar. */
.cmp-bar{display:block;height:10px;border-radius:0 4px 4px 0;min-width:3px}
.cmp-bar.r3{background:var(--cmp-r3)} .cmp-bar.r2{background:var(--cmp-r2)}
.cmp-bar.r1{background:var(--cmp-r1)} .cmp-bar.n{background:var(--cmp-n)}
.cmp-delta{display:block;min-height:15px;margin-top:3px;font-family:var(--cmp-mono);
  font-variant-numeric:tabular-nums;font-size:11px;color:var(--cmp-muted)}
/* Leadership is a word, never a colour: it must survive greyscale and colour blindness, and a
   green "winner" would assert a preference the data cannot support.
   Named .cmp-best, not .cmp-lead — .cmp-lead is the summary container, and sharing the name put
   font-weight:700 on every line of the summary and a stray margin on this tag. */
.cmp-best{color:var(--cmp-ink);font-weight:700}
.post-content p.cmp-empty{margin:0;font-size:12.5px;color:var(--cmp-muted)}

/* The summary carries the weight now, so it gets the emphasis the seven-row grid used to have. */
.cmp-lead{margin-bottom:4px}
.cmp-leadh{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;
  color:var(--cmp-muted);margin-bottom:8px}
.post-content ul.cmp-diffs{list-style:none;margin:0 0 12px;padding:0;display:grid;gap:9px}
.post-content ul.cmp-diffs li{margin:0;padding:0 0 9px;border-bottom:1px solid var(--color-light);
  font-size:12.5px;line-height:1.5;color:var(--cmp-body)}
.post-content ul.cmp-diffs li:last-child{border-bottom:0;padding-bottom:0}
.post-content ul.cmp-diffs li::before{content:none;display:none}
.cmp-diffs b{color:var(--cmp-ink);font-weight:700}
.cmp-diffs em{font-style:normal;color:var(--cmp-muted)}
.cmp-gap{font-family:var(--cmp-mono);font-variant-numeric:tabular-nums;font-size:11.5px;
  font-weight:700;color:var(--cmp-r3)}
.post-content p.cmp-alike{margin:0 0 4px;font-size:12px;line-height:1.55;color:var(--cmp-muted)}
.cmp-alike b{color:var(--cmp-body)}

.cmp-fold{margin:10px 0 0;border-top:1px solid var(--cmp-rule);padding-top:10px}
.post-content .cmp-fold>summary{cursor:pointer;list-style:none;font-size:11.5px;font-weight:600;
  color:var(--cmp-muted);padding:6px 0;min-height:44px;display:flex;align-items:center}
.post-content .cmp-fold>summary::-webkit-details-marker{display:none}
.post-content .cmp-fold>summary::before{content:'+';margin-right:7px;font-family:var(--cmp-mono);
  font-weight:700;color:var(--cmp-ink)}
.post-content .cmp-fold[open]>summary::before{content:'–'}
.post-content .cmp-fold>summary:hover{color:var(--cmp-ink)}
.post-content .cmp-fold>summary:focus-visible{outline:2px solid var(--cmp-ink);outline-offset:2px}

.post-content p.cmp-say{margin:14px 0 0;padding-top:12px;border-top:1px solid var(--cmp-rule);
  font-size:12.5px;line-height:1.6;color:var(--cmp-body)}
.post-content p.cmp-src{margin:10px 0 0;padding-top:10px;border-top:1px solid var(--cmp-rule);
  font-size:11.5px;line-height:1.55;color:var(--cmp-muted)}

@media (max-width:640px){
  .cmp{padding:16px 14px 13px}
  .cmp-picks{grid-template-columns:1fr;gap:8px}
  .cmp-hint{display:none}
  .cmp-head b{font-size:12px}
  /* Three columns leave ~102px each on a phone, which truncated the longest value
     ("388 m · Queenstown") and ate the station name. Values wrap instead of ellipsing;
     uneven cell heights are harmless because each measure is its own block. */
  .cmp-v{font-size:11px;white-space:normal;line-height:1.3}
  .cmp-mlabel{font-size:11px}
  .cmp-mlabel em{font-size:11px}
  .cmp-delta{font-size:11px}
}
</style>
'''

out = HEAD.replace('__DATA__', DATA) + BODY
path = r'C:\TheEnoughPoint-wt-newlaunch\src\components\CondoCompare.astro'
io.open(path, 'w', encoding='utf-8').write(out)
print('written', len(out), 'bytes ·', len(rows), 'projects ·', len({r['d'] for r in rows}), 'districts')
